- hosts: web

  vars_prompt:
          - name: username
            prompt: "Enter the username for SignUp process"
            private: no

          - name: password
            prompt: "Enter the password for the username"  
            

  roles:
  - role: "webserver"

- hosts: mylb
  
  roles:
  - role: "myloadbalancer"


