---
# tasks file for webserver

 - name: "Installing httpd and php"
   package:
           name: "{{ item }}"
           state: present
   loop:
            "{{ software }}"

 - name: "Copying the ifconfig file"
   copy:
           dest: "/var/www/html"
           src: "/var/www/html/ifconfig.php"

 - name: "Starting webserver service"         
   service:
           name: httpd
           state: started

 - name: "Changing Authentication configuration"
   replace:
           dest: "/etc/httpd/conf/httpd.conf"
           regexp: AllowOverride None
           replace: AllowOverride AuthConfig
   notify: restart

 - block:
         - file:
                 path: "/etc/www.passwd"
                 state: file

   rescue:
           - file:
                   path: "/etc/www.passwd"
                   state: touch

 - block:
         - file:
                 path: "{{ httpdpasswdfile }}"
                 state: file
                      
   rescue:
           - file:
                   path: "{{ httpdpasswdfile }}"
                   state: touch

 - blockinfile:
         path: "{{ httpdpasswdfile }}"
         block:
                 AuthName "Role-Check"

                 AuthType Basic

                 AuthUserFile "/etc/www.passwd"

                 Require valid-user
   ignore_errors: true
          
 - block:
         - htpasswd:
                 path: "/etc/www.passwd"  
                 name: "{{ username }}"
                 password: "{{ password }}"
           notify: restart      
   rescue:
           - debug:
                   msg: "Username and Password already exist. Please re-run the playbook and set a new username and password." 
                  

